### PR TITLE
configure the development environment.

### PR DESCRIPTION
**Pull request by fredbelotte**
* Dockerfile.debug for DEV
* Dockerfile.release for STG, PROD
* Dockerup.yml
* Vagrantfile
* Vagrantup.sh

### CODE REVIEW

**Comment by skipbassey** [comment]
Reviewed.

**Comment by fredbelotte** [comment]
can you update the labels, please?

**Comment by fredbelotte** [comment]
am i good to go?

**Comment by skipbassey** [comment]
Yes good to go!

**Pull request merged**
